[Server]
ListenAddr = "0.0.0.0:8080"
MaxRetryCount = 3
[DB]
DBAddr = "rbcustom:rbcustom123456@(175.24.50.211:3306)"
IP = "175.24.50.211"
Port = 3306
User = "rbcustom"
Password = "rbcustom123456"
DBName = "rb_custom"